# 콜백 함수 정리

```js
function repeat1(n) {
  for (var i = 0; i < n; i++) console.log(i);
}

repeat1(5); // 0 1 2 3 4

function repeat2(n) {
  for (var i = 0; i < n; i++) {
    if (i % 2) console.log(i);
  }
}

repeat2(5); // 1 3
```

위의 두 함수는 똑같은 반복문을 돌면서 하는 일이 다르기 때문에 새롭게 정의해서 사용하고 있다. 이를 콜백 함수를 사용하면 공통화시킬 수 있다.

```js
function repeat(n, f) {
  for (var i = 0; i < n; i++) {
    f(i);
  }
}

var logAll = function (i) {
  console.log(i);
};

repeat(5, logAll); // 0 1 2 3 4

var logOdds = function (i) {
  if (i % 2) console.log(i);
};

repeat(5, logOdds); // 1 3
```

이처럼 함수의 매개변수를 통해 다른 함수의 내부로 전달되는 함수를 **콜백 함수**라고 하며, 매개변수를 통해 함수의 외부에서 콜백 함수를 전달받은 함수를 **고차 함수**라고 한다. 고차 함수는 콜백 함수를 자신의 일부분으로 합성한다.

고차 함수는 매개변수를 통해 전달받은 콜백 함수의 호출 시점을 결정해서 호출한다. 다시 말해, 콜백 함수는 고차 함수에 의해 호출되며 이때 고차 함수는 필요에 따라 콜백 함수에 인수를 전달할 수 있다.

<br>

## 비동기 처리를 위한 콜백 함수의 단점

### 비동기 함수

- 함수 내부에 비동기로 동작하는 코드를 포함한 함수
- 비동기 함수 호출 시, 함수 내부의 비동기로 동작하는 코드가 완료되지 않았다 해도 기다리지 않고 즉시 종료
  - 비동기 함수 내부의 비동기로 동작하는 코드는 비동기 함수가 종료된 이후에 완료됨
- 비동기 함수 내부의 비동기로 동작하는 코드에서 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하면 기대한 대로 동작하지 않음 😡
  - 처리 순서가 보장되지 않기 때문
  - 비동기 함수의 처리 결과에 대한 후속 처리는 비동기 함수 내부에서 수행해야 함
  - 일반적으로, 비동기 함수를 범용적으로 사용하기 위해 비동기 함수에 비동기 처리 결과에 대한 후속 처리를 수행하는 콜백 함수를 전달

<br>

### 😈 콜백 지옥 👿

- 콜백 함수를 통해 비동기 처리 결과에 대한 후속 처리를 수행하는 비동기 함수가 비동기 처리 결과를 가지고 또다시 비동기 함수를 호출한다면, 콜백 함수 호출이 중첩되어 복잡도가 높아짐
- 이런 현상을 '콜백 지옥'이라고 함

<br>

### 콜백에서의 에러 처리 한계

```js
try {
  setTimeout(() => {
    throw new Error('Error 발생');
  }, 1000);
} catch (e) {
  console.error(e);
}
```

위의 코드에서 1초 뒤에 setTimeout이 에러를 던짐에도 catch 문은 이를 캐치하지 못한다.

에러는 호출자 방향으로 전파된다. 즉, 콜 스택의 아래 방향(실행 중인 실행 컨텍스트가 푸시되기 직전에 푸시된 실행 컨텍스트 방향)으로 전파된다. 하지만 setTimeout 함수의 콜백 함수를 호출한 것은 setTimeout 함수가 아니므로(setTimeout의 콜백 함수가 실행될 때 이미 setTimeout은 콜 스택에서 제거된 상태) catch 블록이 이를 캐치할 수 없다.

<br>

## 프로미스(Promise)

- 비동기 처리 상태와 처리 결과를 관리하는 객체
- Promise 생성자 함수를 new 연산자와 함께 호출하면 프로미스 객체를 생성
- Promise 생성자 함수는 비동기 처리를 수행할 콜백 함수(executor 함수)를 인수로 전달받는데, 이 콜백 함수는 resolve와 reject 함수를 인수로 전달받음

```js
const promise = new Promise((resolve, reject) => {
  if (/* 비동기 처리 성공 */) {
    resolve('result');
  } else { /* 비동기 처리 실패 */
    reject('failure reason');
  }
});
```

| 프로미스의 상태 정보 | 의미                                  | 상태 변경 조건                   |
| -------------------- | ------------------------------------- | -------------------------------- |
| pending              | 비동기 처리가 아직 수행되지 않은 상태 | 프로미스가 생성된 직후 기본 상태 |
| fulfilled            | 비동기 처리가 수행된 상태(성공)       | resolve 함수 호출                |
| rejected             | 비동기 처리가 수행된 상태(실패)       | reject 함수 호출                 |

- 비동기 처리 성공: resolve 함수를 호출하여 프로미스를 fulfilled 상태로 변경
- 비동기 처리 실패: reject 함수를 호출하여 프로미스를 rejected 상태로 변경

- `settled` 상태
  - pending이 아닌 상태로 비동기 처리가 수행된 상태
    - fulfilled, rejected
  - 일단 한번 이 상태가 되면 다른 상태로 변화할 수 없음

<br>

### 프로미스 후속 처리

- 프로미스의 비동기 처리 상태가 변화하면 후속 처리 메서드에 인수로 전달한 콜백 함수가 선택적으로 호출됨

#### Promise.prototype.then

- 첫 번째 콜백 함수는 프로미스가 fulfilled 상태(resolve 함수가 호출된 상태)가 되면 호출됨
  - 이때 콜백 함수는 프로미스의 비동기 처리 결과를 인수로 전달받음
- 두 번째 콜백 함수는 프로미스가 rejected 상태(reject 함수가 호출된 상태)가 되면 호출됨
  - 이때 콜백 함수는 프로미스의 에러를 인수로 전달받음

```js
// fulfilled
new Promise(resolve => resolve('fulfilled')).then(
  v => console.log(v),
  e => console.error(e),
); // fulfilled

// rejected
new Promise((_, reject) => reject(new Error('rejected'))).then(
  v => console.log(v),
  e => console.error(e),
); // Error: rejected
```

<br>

#### Promise.prototype.catch

- 한 개의 콜백 함수를 인수로 전달받음
- 프로미스가 rejected 상태인 경우에만 호출됨
- catch 호출 시 내부적으로 then(undefined, onRejected)를 호출

```js
new Promise((_, reject) => reject(new Error('rejected'))).catch(e =>
  console.log(e),
); // Error: rejected
```

<br>

#### Promise.prototype.finally

- 한 개의 콜백 함수를 인수로 전달받음
- 프로미스의 성공 실패 여부와 상관없이 무조건 한 번 호출됨
- 프로미스 상태와 상관없이 공통적으로 수행해야 할 처리 내용이 있을 때 유용

```js
new Promise(() => {}).finally(() => console.log('finally')); // finally
```

<br>

### 프로미스 에러 처리

1. then 메서드의 두 번째 콜백 함수 사용
   - 첫 번째 콜백 함수에서 에러 발생 시 이를 캐치하지 못함
   - 코드가 복잡해져서 가독성이 좋지 않음
2. catch 메서드 사용
   - then 메서드 호출 이후에 호출하면 비동기 처리에서 발생한 에러뿐만 아니라 then 메서드 내부에서 발생한 에러까지 모두 캐치 가능
   - then 사용 시보다 가독성이 좋고 명확함

<br>

### 프로미스 체이닝

```js
const url = 'https://url.com';

promiseGet(`${url}/posts/1`)
  .then({ userId } => promiseGet(`${url}/users/${userId}`))
  .then(userInfo => console.log(userInfo))
  .catch(err => console.error(err));
```

- 위의 예시에서는 `then -> then -> catch` 후속 처리 메서드를 호출
  - 이를 '프로미스 체이닝'이라고 함

| 후속 처리 메서드 | 콜백 함수의 인수                                                                       | 후속 처리 메서드의 반환값                             |
| ---------------- | -------------------------------------------------------------------------------------- | ----------------------------------------------------- |
| then             | promiseGet 함수가 반환한 프로미스가 resolve한 값(id가 1인 post)                        | 콜백 함수가 반환한 프로미스                           |
| then             | 첫 번째 then 메서드가 반환한 프로미스가 resolve한 값(post의 userId로 취득한 user 정보) | 콜백 함수가 반환한 값(undefined)을 resolve한 프로미스 |
| catch            | promiseGet 함수 또는 앞선 후속 처리 메서드가 반환한 프로미스가 reject한 값             | 콜백 함수가 반환한 값(undefined)을 resolve한 프로미스 |

<br>

### 프로미스 정적 메서드

#### Promise.resolve / Promise.reject

- 이미 존재하는 값을 래핑하여 프로미스를 생성하기 위해 사용

```js
// resolve
const resolvedPromise = Promise.resolve([1, 2, 3]);
resolvedPromise.then(console.log); // [1, 2, 3]

// reject
const rejectedPromise = Promise.reject(new Error('Error'));
rejectedPromise.catch(console.log); // Error: Error
```

<br>

#### Promise.all

- 여러 개의 비동기 처리를 모두 병렬 처리할 때 사용
- 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받음
  - 전달받은 모든 프로미스가 fulfilled 상태가 되면 모든 처리 결과를 배열에 저장해 새로운 프로미스를 반환
    - 배열은 전달받은 프로미스 순서대로 저장
      - 처리 순서 보장!
- Promise.all 메서드가 종료하는 데 걸리는 시간은 가장 늦게 fulfilled 상태가 되는 프로미스의 처리 시간보다 조금 더 긺
- 인수로 전달 받은 배열의 프로미스 중 하나라도 rejected 상태가 되면 나머지 프로미스를 기다리지 않고 에러를 reject하는 새로운 프로미스를 즉시 반환
- 인수로 전달 받은 이터러블의 요소가 프로미스가 아닌 경우 Promise.resolve 메서드를 통해 프로미스로 래핑

```js
const requestData1 = () =>
  new Promise(resolve => setTimeout(() => resolve(1), 3000));
const requestData2 = () =>
  new Promise(resolve => setTimeout(() => resolve(2), 2000));
const requestData3 = () =>
  new Promise(resolve => setTimeout(() => resolve(3), 1000));

Promise.all([requestData1(), requestData2(), requestData3()])
  .then(console.log) // [1, 2, 3] -> 약 3초 소요
  .catch(console.error);
```

<br>

#### Promise.race

- 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받음
- 모든 프로미스가 fulfilled 상태가 되는 것을 기다리지 않고, 가장 먼저 fulfilled 상태가 된 프로미스의 처리 결과를 resolve하는 새로운 프로미스를 반환
- 인수로 전달 받은 배열의 프로미스 중 하나라도 rejected 상태가 되면 나머지 프로미스를 기다리지 않고 에러를 reject하는 새로운 프로미스를 즉시 반환

```js
Promise.race([
  new Promise(resolve => setTimeout(() => resolve(1), 3000)),
  new Promise(resolve => setTimeout(() => resolve(2), 2000)),
  new Promise(resolve => setTimeout(() => resolve(3), 1000)),
])
  .then(console.log)
  .catch(console.log);
```

<br>

#### Promise.allSettled

- 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받음
- 전달받은 프로미스가 모두 settled 상태가 되면 처리 결과를 배열로 반환
  - 프로미스가 fulfilled 상태인 경우 비동기 처리 상태를 나타내는 status 프로퍼티와 처리 결과를 나타내는 value 프로퍼티를 가짐
  - 프로미스가 rejected 상태인 경우 비동기 처리 상태를 나타내는 status 프로퍼티와 에러를 나타내는 reason 프로퍼티를 가짐

```js
Promise.allSettled([
  new Promise(resolve => setTimeout(() => resolve(1), 2000)),
  new Promise((_, reject) =>
    setTimeout(() => reject(new Error('Error!')), 1000),
  ),
]).then(console.log);
/*
[
  {status: "fulfilled", value: 1},
  {status: "rejected", reason: Error: Error! at <anonymous>:3:54}
]
*/
```

<br>

## 마이크로태스크 큐

```js
setTimeout(() => console.log(1), 0);

Promise.resolve()
  .then(() => console.log(2))
  .then(() => console.log(3));
```

위 예제에서 `1 -> 2 -> 3` 의 순으로 출력되기를 바랐으나, 실제로는 `2 -> 3 -> 1`의 순으로 출력된다. 프로미스의 후속 처리 메서드의 콜백 함수는 태스크 큐가 아니라 마이크로태스크 큐에 저장되기 때문이다.

- 프로미스 후속 처리 메서드의 콜백 함수 → 마이크로 태스크 큐
- 비동기 함수의 콜백 함수나 이벤트 핸들러 → 태스크 큐

마이크로태스크 큐는 태스크 큐보다 우선순위가 높다. 이벤트 루프는 콜 스택이 비면 먼저 마이크로태스크 큐에서 대기하고 있는 함수를 가져와 실행한다. 이후 마이크로태스크 큐가 비면 태스크 큐에서 대기하고 있는 함수를 가져와 실행한다.

<br>

## fetch

```js
const promise = fetch(url [, options])
```

- fetch 함수는 HTTP 응답을 나타내는 Response 객체를 래핑한 Promise 객체를 반환
- fetch 함수가 반환하는 프로미스는 기본적으로 `404 Not Found`나 `500 Internal Server Error`와 같은 HTTP 에러가 발생해도 에러를 reject하지 않고 불리언 타입의 ok 상태를 false로 설정한 Response 객체를 resolve함
  - 오프라인 등의 네트워크 장애나 CORS 에러에 의해 요청이 완료되지 못한 경우에만 프로미스를 reject

<br>

## Generator

```js
var addCoffee = function (prevName, name) {
  setTimeout(function () {
    coffeeMaker.next(prevName ? prevName + ', ' + name : name);
  }, 500);
};
var coffeeGenerator = function* () {
  var espresso = yield addCoffee('', '에스프레소');
  console.log(espresso);
  var americano = yield addCoffee(espresso, '아메리카노');
  console.log(americano);
  var mocha = yield addCoffee(americano, '카페모카');
  console.log(mocha);
  var latte = yield addCoffee(mocha, '카페라떼');
  console.log(latte);
};
var coffeeMaker = coffeeGenerator();
coffeeMaker.next();
```

- 위의 예시 코드처럼 `*`이 붙은 함수가 Generator 함수
- Generator 함수 실행 시 Iterator가 반환
  - Iterator는 next라는 메서드를 가지고 있음
    - next 메서드 호출 시 함수 내부에서 가장 먼저 등장하는 yield에서 함수의 실행을 멈춤
    - 그리고 순차적으로 다음에 나오는 yield에서 실행을 멈춤
    - 이를 사용하여 동기 표현

<br>

## async / await

- 프로미스를 기반으로 동작
- 비동기 처리 결과를 후속 처리(then/catch/finally)할 필요 없이 동기 처리처럼 프로미스 사용 가능

<br>

### async 함수

- async 함수는 async 키워드를 사용하여 정의하며, 언제나 프로미스 반환
  - 암묵적으로 반환값을 resolve하는 프로미스 반환

<br>

### await 키워드

- await 키워드는 반드시 async 함수 내부에서 사용해야 함
- 프로미스가 settled 상태가 될 때까지 대기하다가 settled 상태가 되면 프로미스가 resolve한 처리 결과를 반환
- 이 키워드는 반드시 프로미스 앞에서 사용해야 함

<br>

### 에러 처리

- async/await에서는 try...catch 문을 사용하여 에러 처리가 가능
- 만약 async 함수 내에서 catch 문을 사용해서 에러 처리를 하지 않으면 async 함수는 발생한 에러를 reject하는 프로미스 반환
